# 1.导入numpy库并简写为 np

In [2]:
import numpy as np

# 2.打印numpy的版本和配置说明

In [4]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/JupyterNoteBook\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/JupyterNoteBook\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/JupyterNoteBook\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/JupyterNoteB

# 3.创建一个长度为10的空向量

In [8]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 4.如何找到任何一个数组的内存大小？

In [7]:
Z = np.zeros((10,10))
print("%d bytes"% (Z.size * Z.itemsize))

800 bytes


# 5.如何从命令行得到numpy中add函数的说明文档

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

# 6.创建一个长度为10并且除了第五个值为1的空向量

In [16]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 7.创建一个值域范围从10到49的向量

In [17]:
Z = np.arange(10,50)
print (Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8.反转一个向量（第一个元素变为最后一个）

In [18]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# 9.创建一个3x3并且值从0到8的矩阵

In [19]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10.找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [21]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


# 11.创建一个3x3的单位矩阵

In [22]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 12.创建一个3x3x3的随机数组

In [23]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.1565799  0.55832119 0.58581231]
  [0.53329096 0.97214877 0.83674547]
  [0.04566985 0.62296024 0.18887286]]

 [[0.69053574 0.13819127 0.99914119]
  [0.95983115 0.71338296 0.55857912]
  [0.07096761 0.06489141 0.38082901]]

 [[0.23818787 0.82328876 0.50974164]
  [0.27999072 0.42803208 0.24862002]
  [0.46102777 0.12554703 0.84597102]]]


# 13.创建一个10x10的随机数组并找到它的最大值和最小值

In [27]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.01336256447671258 0.9974556709023574


# 14.创建一个长度为30的随机向量并找到它的平均值

In [28]:
Z = np.random.random(30)
m = Z.mean()
print (m)

0.4747289527721013


# 15.创建一个二维数组，其中边界值为1其余值为0

In [29]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 16.对于一个存在在数组，如何添加一个用0填充的边界？

In [30]:
Z = np.ones((5,5))
Z = np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 17.以下表达式运行的结果分别是什么？
 0 * np.nan
 np.nan == np.nan
 np.inf > np.nan
 np.nan - np.nan
 0.3 == 3 * 0.1

In [31]:
print(0 * np.nan)

nan


In [32]:
print(np.nan == np.nan)

False


In [33]:
print(np.inf > np.nan)

False


In [34]:
print(np.nan - np.nan)

nan


In [35]:
print(0.3 == 3 * 0.1)

False


# 18.创建一个5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [38]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 19.创建一个8X8的矩阵，并且设置成棋盘的样式

In [36]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 20.考虑一个（6,7,8）形状的数组，其第100个元素的索引（X,Y,Z）是什么？

In [39]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


# 21.用tile函数去创建一个8x8的棋盘样式矩阵

In [40]:
Z = np.tile( np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 22.对一个5x5的随机矩阵做归一化

In [41]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.13767668 0.56073496 0.26140371 0.09448313 0.68006386]
 [0.38294485 0.         0.55307784 0.49551928 0.27953626]
 [0.08523866 0.54016374 0.8009591  0.81778153 0.73325072]
 [0.83934622 0.8218718  0.59616514 0.65918663 1.        ]
 [0.70375243 0.9938563  0.51805925 0.94664189 0.35446447]]


# 23.创建一个颜色描述为（RGBA）四个无符号字节的自定义dtype?

In [43]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

# 24.一个5X3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [44]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# 25.给定一个一维数组，对其在3到8之间的所有元素取反

In [46]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


# 26.下面脚本运行后的结果是什么？
print(sum(range(5),-1))
form numpy import *
print(sum(range(5),-1))

In [47]:
print(sum(range(5),-1))

9


In [50]:
from numpy import *
print(sum(range(5),-1))

10


# 27.考虑一个整数向量Z，下列表达合法的是哪个？
Z**Z
2 << Z >> 2
Z <- Z
lj*Z
Z/1/1
Z<Z<Z

In [51]:
Z = np.arange(5)
Z ** Z  # legal

array([  1,   1,   4,  27, 256], dtype=int32)

In [52]:
Z = np.arange(5)
2 << Z >> 2  # false

array([0, 1, 2, 4, 8], dtype=int32)

In [54]:
Z = np.arange(5)
Z <- Z   # legal

array([False, False, False, False, False])

In [56]:
Z = np.arange(5)
lj*Z   #legal

NameError: name 'lj' is not defined

In [57]:
Z = np.arange(5)
Z/1/1 # legal

array([0., 1., 2., 3., 4.])

In [61]:
Z = np.arange(5)
Z<Z>Z  # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# 28.下列表达式的结果分别是什么？
np.array(0) / np.array(0）
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [62]:
print(np.array(0) / np.array(0))

nan


D:\JupyterNoteBook\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [64]:
print(np.array(0) // np.array(0))

0


D:\JupyterNoteBook\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [65]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


# 29.如何从零位对浮点数组做舍入

In [68]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)),Z))

[-9. 10. -3. -2.  7. -5. 10. 10. -2. -8.]


# 30.如何找到两个数组中的共同元素？

In [75]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 8 9]


# 31.如何忽略所有的numpy警告（尽管不建议这么做）？

In [76]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

# 32.下面的表达式是正确的吗？
np.sqrt(-1) == np.emath.sqrt(-1)

In [78]:
np.sqrt(-1) == np.emath.sqrt(-1)  #False

D:\JupyterNoteBook\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

# 33.如何得到昨天，今天，明天的日期？

In [81]:
yesterday = np.datetime64("today","D") - np.timedelta64(1,"D")
today     = np.datetime64("today","D")
tomorrow  = np.datetime64("today","D") + np.timedelta64(1,"D")
print ("Yesterday is " + str(yesterday))
print ("Today is " + str (today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


# 34.如何得到所有与2016年7月对应的日期

In [82]:
Z = np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 35.如何直接在位计算（A+B)\*(-A/2)(不建立副本)？

In [84]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

# 36.用五种不同的方法去提取一个随机数组的整数部分

In [85]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)

[6. 5. 8. 4. 0. 9. 8. 4. 0. 0.]


In [91]:
Z = np.random.uniform(0,10,10)
print (np.floor(Z))

[6. 7. 9. 4. 7. 9. 1. 1. 8. 6.]


In [92]:
print (np.ceil(Z)-1)

[6. 7. 9. 4. 7. 9. 1. 1. 8. 6.]


In [93]:
print (Z.astype(int))

[6 7 9 4 7 9 1 1 8 6]


In [94]:
print (np.trunc(Z))

[6. 7. 9. 4. 7. 9. 1. 1. 8. 6.]


# 37.创建一个5x5的矩阵，其中每行的数值范围从0到4

In [95]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 38.通过考虑一个可生成10个整数的函数，来构建一个数组

In [96]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 39.创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [97]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 40.创建一个长度为10的随机向量，并将其排序

In [98]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.0542553  0.09136565 0.20431428 0.42125482 0.45193886 0.68176697
 0.71010992 0.79944143 0.83377636 0.94880751]


# 41.对于一个小数组，如何用比np.sum更快的方式对其求和？

In [101]:
Z = np.arange(10)
np.add.reduce(Z)

45

# 42.对于两个随机数组A和B，检查他们是否相等

In [102]:
#方法一
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
#Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

True


In [103]:
#方法二
#Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

True


# 43.创建一耳光只读数组（read-only)

In [104]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

# 44.将笛卡尔坐标下的一个10X2的矩阵转换成极坐标形式

In [105]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.72480298 0.97592984 0.55604568 0.92355747 0.96763387 1.06608683
 1.08761485 1.10495099 0.97691817 0.82656136]
[0.44371319 1.29815199 0.98881907 0.55491499 0.85301489 0.48715412
 0.68533897 0.98413121 0.68732562 1.30017622]


# 45.创建一个长度为10的向量，并将向量中最大值替换为1

In [107]:
Z = np.zeros((5,5),[("x",float),("y",float)])
Z["x"],Z["y"] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# 46.创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域

In [111]:
Z = np.zeros((5,5),[("x",float),("y",float)])
Z["x"],Z["y"] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# 47.给定两个数组X和Y，构造Cauchy矩阵C （Cij =1/(xi - yi)

In [112]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


# 48.打印每个numpy标量类型中最小值和最大值

In [113]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [114]:
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# 49.如何打印一个数组中的所有数值？

In [120]:
#np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 50.给定标量时，如何找到数组中最接近标量的值？

In [127]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

2


# 51.创建一个表示位置（x,y）和颜色（r,g,b）的结构化数组

In [131]:
Z = np.zeros(10,[("position",[("x",float,1),
                               ("y",float,1)]),
                ("color",     [("r",float,1),
                               ("g",float,1),
                               ("b",float,1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


# 52.对一个表示坐标形状为（100.2）的随机向量，找到点与点的距离

In [135]:
#方法一
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 +(Y-Y.T)**2)
print(D)

[[0.         0.10529923 0.90792352 0.9852586  0.98317234 0.28093929
  0.9083417  0.53346716 0.29115588 0.62015162]
 [0.10529923 0.         0.80297885 0.89092384 0.87824596 0.32519951
  0.80359679 0.50428876 0.36171343 0.57708737]
 [0.90792352 0.80297885 0.         0.34635097 0.07528195 1.00032171
  0.01757428 0.82694591 1.08457241 0.7708279 ]
 [0.9852586  0.89092384 0.34635097 0.         0.34903535 0.97865039
  0.32878391 0.70118998 1.07383276 0.6091935 ]
 [0.98317234 0.87824596 0.07528195 0.34903535 0.         1.07225737
  0.07653231 0.88807949 1.15740096 0.82650797]
 [0.28093929 0.32519951 1.00032171 0.97865039 1.07225737 0.
  0.99586025 0.35246956 0.0966806  0.46179027]
 [0.9083417  0.80359679 0.01757428 0.32878391 0.07653231 0.99586025
  0.         0.81708973 1.08087937 0.75927988]
 [0.53346716 0.50428876 0.82694591 0.70118998 0.88807949 0.35246956
  0.81708973 0.         0.44428177 0.11193001]
 [0.29115588 0.36171343 1.08457241 1.07383276 1.15740096 0.0966806
  1.08087937 0.444281

In [136]:
#方法二
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulsan (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.10529923 0.90792352 0.9852586  0.98317234 0.28093929
  0.9083417  0.53346716 0.29115588 0.62015162]
 [0.10529923 0.         0.80297885 0.89092384 0.87824596 0.32519951
  0.80359679 0.50428876 0.36171343 0.57708737]
 [0.90792352 0.80297885 0.         0.34635097 0.07528195 1.00032171
  0.01757428 0.82694591 1.08457241 0.7708279 ]
 [0.9852586  0.89092384 0.34635097 0.         0.34903535 0.97865039
  0.32878391 0.70118998 1.07383276 0.6091935 ]
 [0.98317234 0.87824596 0.07528195 0.34903535 0.         1.07225737
  0.07653231 0.88807949 1.15740096 0.82650797]
 [0.28093929 0.32519951 1.00032171 0.97865039 1.07225737 0.
  0.99586025 0.35246956 0.0966806  0.46179027]
 [0.9083417  0.80359679 0.01757428 0.32878391 0.07653231 0.99586025
  0.         0.81708973 1.08087937 0.75927988]
 [0.53346716 0.50428876 0.82694591 0.70118998 0.88807949 0.35246956
  0.81708973 0.         0.44428177 0.11193001]
 [0.29115588 0.36171343 1.08457241 1.07383276 1.15740096 0.0966806
  1.08087937 0.444281

# 53.如何将32位的浮点数（float）转换为对应的整数（integer）？

In [137]:
Z = np.arange(10,dtype=np.int32)
Z = Z.astype(np.float32,copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 54.如何读取以下文件？
1,2,3,4,5 
6，，，7,8,
，，9,10,11

In [158]:
from io import StringIO

# Fake file
s = StringIO("""1,2,3,4,5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


# 55.对于numpy数组，enumerate的等价操作时什么？

In [159]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index,value)
    for index in np.ndindex(Z.shape):
        print (index,Z[index])

(0, 0) 0
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 1) 1
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 2) 2
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(1, 0) 3
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(1, 1) 4
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(1, 2) 5
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(2, 0) 6
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(2, 1) 7
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


# 56.生成一个通用的二维Gaussian-linke数组

In [162]:
X,Y =np.meshgrid( np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma,mu =1.0,0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2)))
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

# 57.对于一个二维数组，如何在其内部随机放置p个元素？

In [164]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 58.减去一个矩阵中的每一行的平均值

In [165]:
X = np.random.rand(5,10)
#Recent versions of numpy
Y = X -X.mean(axis=1, keepdims=True)
print(Y)

[[-1.99043507e-01  3.94365890e-01  4.10531703e-01 -7.10465847e-02
  -1.13125567e-01 -1.89103321e-01  7.82096093e-02 -2.29517743e-01
  -2.50609682e-01  1.69339203e-01]
 [ 3.52240645e-01 -2.29799241e-01 -2.47612163e-01  2.24090713e-01
   1.11311796e-02 -4.16543954e-01 -4.54592828e-02 -3.95970928e-01
   5.06178677e-01  2.41744356e-01]
 [-4.33788837e-01 -3.34289278e-01  3.05970652e-01  1.81634532e-01
  -9.57693444e-03 -1.51992642e-01  1.97034952e-01 -1.37705808e-01
   2.39559974e-01  1.43153391e-01]
 [-1.61882792e-01  1.57030800e-01 -2.60944927e-01 -7.19360881e-02
   3.17268074e-01  6.05763699e-01 -3.35992206e-01  2.59164225e-02
  -2.74773254e-01 -4.49729269e-04]
 [-1.95419122e-01  1.05445940e-01 -1.12569724e-01  2.09335153e-01
  -4.00595957e-01  2.92360538e-01  2.21330185e-01 -2.81162651e-01
  -3.29200931e-01  4.90476569e-01]]


In [166]:
#方法二
#Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1,1)
print(Y)

[[-1.99043507e-01  3.94365890e-01  4.10531703e-01 -7.10465847e-02
  -1.13125567e-01 -1.89103321e-01  7.82096093e-02 -2.29517743e-01
  -2.50609682e-01  1.69339203e-01]
 [ 3.52240645e-01 -2.29799241e-01 -2.47612163e-01  2.24090713e-01
   1.11311796e-02 -4.16543954e-01 -4.54592828e-02 -3.95970928e-01
   5.06178677e-01  2.41744356e-01]
 [-4.33788837e-01 -3.34289278e-01  3.05970652e-01  1.81634532e-01
  -9.57693444e-03 -1.51992642e-01  1.97034952e-01 -1.37705808e-01
   2.39559974e-01  1.43153391e-01]
 [-1.61882792e-01  1.57030800e-01 -2.60944927e-01 -7.19360881e-02
   3.17268074e-01  6.05763699e-01 -3.35992206e-01  2.59164225e-02
  -2.74773254e-01 -4.49729269e-04]
 [-1.95419122e-01  1.05445940e-01 -1.12569724e-01  2.09335153e-01
  -4.00595957e-01  2.92360538e-01  2.21330185e-01 -2.81162651e-01
  -3.29200931e-01  4.90476569e-01]]


# 59.如何通过第n列对一个数组进行排序

In [168]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 0 4]
 [7 3 3]
 [2 1 9]]
[[5 0 4]
 [2 1 9]
 [7 3 3]]


# 60.如何检查一个二维数组是否有空列？

In [170]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


# 61.从数组中的给定值中找出最近的值

In [169]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5086517115429299


# 62.如何用迭代器（iterator）计算两个分别具有形状（1,3）和（3,1）的数组？

In [171]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x + y
    print (it.operands[2])

[[0 0 4]
 [7 3 3]
 [2 1 9]]
[[0 1 4]
 [7 3 3]
 [2 1 9]]
[[0 1 2]
 [7 3 3]
 [2 1 9]]
[[0 1 2]
 [1 3 3]
 [2 1 9]]
[[0 1 2]
 [1 2 3]
 [2 1 9]]
[[0 1 2]
 [1 2 3]
 [2 1 9]]
[[0 1 2]
 [1 2 3]
 [2 1 9]]
[[0 1 2]
 [1 2 3]
 [2 3 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


# 63.创建一个具有name属性的数组类

In [176]:
class NamedArray(np.ndarray):
    def __new__(cls,array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj,"name","no name")
        
Z = NamedArray(np.arange(10),"range_10")
print (Z.name)

range_10


# 64.考虑一个给定的向量，如何对由第二个向量索引的每个元素加1（小心重复的索引）？

In [177]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 2. 4. 2. 7. 2. 1. 2. 5. 3.]


# 65.根据索引列表（I），如何将向量（X）的元素累加到数组（F）?

In [178]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


# 66.考虑一个（dtype=ubyte)d (w,h,3)图像，计算其唯一颜色的数量

In [179]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should computer 256*256 first.
#Otherwise numpy will only [romote F.dtype to "uint16" and oversolw will occur]
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


# 67.考虑一个四维数组，如何一次性计算出最后两个轴（axis）的和？

In [180]:
A = np.random.randint(0,10,(3,4,3,4))
#solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[57 57 55 52]
 [54 58 37 50]
 [58 49 66 44]]


# 68.考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

In [182]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S,weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.51938035 0.41989122 0.44838048 0.65917719 0.42982339 0.37977149
 0.61637963 0.59141275 0.42627777 0.4356141 ]


# 69.如何获得点积dot prodcut的对角线？

In [183]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow versiom
np.diag(np.dot(A,B))

array([1.12668956, 1.91292376, 1.58481707, 0.39551219, 1.03177775])

In [184]:
#方法二
#Fast version
np.sum(A * B.T, axis=1)

array([1.12668956, 1.91292376, 1.58481707, 0.39551219, 1.03177775])

In [185]:
#方法三
#Faster version
np.einsum("ij,ji->i",A,B)

array([1.12668956, 1.91292376, 1.58481707, 0.39551219, 1.03177775])

# 70.考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中么个值之间有3个连续的零？

In [186]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# 71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？

In [187]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


# 72. 如何对一个数组中任意两行做交换?

In [188]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 73. 考虑一组描述10个三角形（具有共享顶点）的10个三元组，找到组成所有三角形的唯一线段的集合

In [189]:
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 26) ( 0, 92) ( 1, 33) ( 1, 85) ( 4,  8) ( 4, 20) ( 4, 37) ( 4, 60)
 ( 4, 97) ( 4, 99) ( 8, 37) (11, 53) (11, 90) (15, 44) (15, 47) (20, 99)
 (26, 28) (26, 76) (26, 92) (28, 76) (33, 85) (44, 47) (48, 65) (48, 87)
 (52, 57) (52, 83) (53, 90) (57, 83) (60, 97) (65, 87)]


# 74. 给定一个bincount的数组C，如何生成一个数组A，使得 np.bincount(A) == C? 

In [190]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


# 75. 如何使用数组上的滑动窗口计算平均值？

In [192]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


# 76. 考虑一维数组Z，构建一个二维数组，其第一行为(Z[0],Z[1],Z[2])，每个后续行移1 行 (最后一行应该是Z[-3],Z[-2],Z[-1])

In [193]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


# 77. 如何否定布尔值，或改变浮点数的符号？

In [194]:
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.84269063,  0.3390267 , -0.37151277, -0.48460128,  0.28366314,
       -0.93308919,  0.97896292, -0.11110633,  0.94821979,  0.0374659 ,
       -0.43083833,  0.50645516,  0.22877705,  0.39825191, -0.07548242,
       -0.15485772,  0.09441742, -0.5102413 ,  0.49068449,  0.04028994,
        0.97699243, -0.79124936,  0.51723748,  0.45761178,  0.33767406,
       -0.38348113, -0.55015281, -0.53280445, -0.90024941,  0.1679282 ,
        0.11372879, -0.90411901,  0.38201083,  0.70073206, -0.30667385,
       -0.61895381,  0.33677048, -0.96351555, -0.16068399,  0.27514189,
        0.13182871, -0.83899405, -0.3100058 , -0.67911032,  0.26078013,
       -0.51497488,  0.52782662, -0.49882889,  0.31814303, -0.25085647,
        0.84459253,  0.72328749,  0.40076852,  0.21833492,  0.5463251 ,
       -0.83519972, -0.22280937, -0.78362928, -0.89846953, -0.65526807,
       -0.02398134,  0.85935701, -0.01363641,  0.98305979, -0.48054811,
        0.61613527, -0.70873982, -0.42790529,  0.94393905,  0.71

# 78.考虑2组点P0，P1描述线（2d）和点p，如何计算从p到每条线的距离i (P0[i],P1[i])?

In [195]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.61083522  5.91244741  1.20291871 10.87396293 19.83625097  1.99342845
  3.30982759 14.77450776  1.09198865  1.06008983]


# 79. 考虑2组点P0，P1描述线（2d）和一组点P，如何计算从每个点j (P[j])到每条线的距离i (P0[i],P1[i])?

In [196]:
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[4.21916328e+00 2.07465183e+00 3.31173395e+00 4.15633629e+00
  2.94827074e+00 5.01682383e+00 9.17900419e-01 3.28986451e+00
  1.17288826e+01 7.14256124e+00]
 [1.40184514e+00 1.04062262e+00 2.61805041e+00 6.87315902e+00
  9.38122273e-03 8.10419586e+00 6.53517942e-01 2.72287890e-01
  8.77063953e+00 9.84971757e+00]
 [3.01282523e+00 3.65678560e+00 3.81852973e+00 1.13501277e+01
  3.69445644e+00 1.09619709e+01 5.71806153e+00 8.48420010e-01
  5.15401936e+00 1.43537150e+01]
 [5.68747010e+00 9.35419429e-01 1.32170016e+01 2.81530623e+00
  2.34114571e+00 7.52112323e+00 1.17718395e+01 5.24458710e+00
  1.09161347e+01 5.72869805e+00]
 [2.10191790e-01 3.06236186e+00 1.23061494e+00 8.98780689e+00
  2.09574429e+00 1.01502616e+01 5.02625145e-01 1.18808595e+00
  6.66951998e+00 1.19637192e+01]
 [8.36127054e+00 6.43421358e+00 8.60834454e+00 8.87996758e+00
  3.56072906e+00 1.31238892e+01 7.75010407e+00 8.77289138e+00
  5.03991530e+00 1.17966154e+01]
 [6.36650339e+00 1.97359070e+00 1.26033404e+01 3.86413660e

# 80. 考虑一个任意数组，编写一个函数，提取具有固定形状的子部分并以给定元素为中心（必要时使用“fill”值填充）

In [198]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 6 1 6 0 3 3 6 4 6]
 [2 9 9 7 4 6 8 6 5 8]
 [0 5 9 0 5 2 1 3 4 3]
 [4 8 5 9 9 0 8 4 6 9]
 [0 2 6 0 7 6 4 5 3 9]
 [5 4 6 9 2 5 1 0 5 6]
 [6 6 5 7 1 2 4 7 9 3]
 [2 9 5 8 4 1 8 8 5 7]
 [4 0 9 2 6 4 8 6 3 7]
 [0 8 7 5 2 1 8 2 8 1]]
[[0 0 0 0 0]
 [0 9 6 1 6]
 [0 2 9 9 7]
 [0 0 5 9 0]
 [0 4 8 5 9]]


D:\JupyterNoteBook\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


# 81. 考虑一个数组 Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], 如何生成一个数组 R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [199]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# 82. 计算矩阵排名

In [201]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


# 83. 如何在数组中找到最常见的值？

In [202]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


# 84. 从随机10x10矩阵中提取所有连续的3x3块

In [203]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 1 1]
   [0 3 2]
   [4 4 1]]

  [[1 1 2]
   [3 2 4]
   [4 1 1]]

  [[1 2 4]
   [2 4 4]
   [1 1 0]]

  [[2 4 3]
   [4 4 4]
   [1 0 2]]

  [[4 3 3]
   [4 4 1]
   [0 2 0]]

  [[3 3 2]
   [4 1 0]
   [2 0 1]]

  [[3 2 3]
   [1 0 3]
   [0 1 4]]

  [[2 3 0]
   [0 3 4]
   [1 4 0]]]


 [[[0 3 2]
   [4 4 1]
   [4 0 3]]

  [[3 2 4]
   [4 1 1]
   [0 3 2]]

  [[2 4 4]
   [1 1 0]
   [3 2 4]]

  [[4 4 4]
   [1 0 2]
   [2 4 4]]

  [[4 4 1]
   [0 2 0]
   [4 4 3]]

  [[4 1 0]
   [2 0 1]
   [4 3 3]]

  [[1 0 3]
   [0 1 4]
   [3 3 0]]

  [[0 3 4]
   [1 4 0]
   [3 0 2]]]


 [[[4 4 1]
   [4 0 3]
   [2 2 0]]

  [[4 1 1]
   [0 3 2]
   [2 0 2]]

  [[1 1 0]
   [3 2 4]
   [0 2 3]]

  [[1 0 2]
   [2 4 4]
   [2 3 3]]

  [[0 2 0]
   [4 4 3]
   [3 3 0]]

  [[2 0 1]
   [4 3 3]
   [3 0 4]]

  [[0 1 4]
   [3 3 0]
   [0 4 2]]

  [[1 4 0]
   [3 0 2]
   [4 2 4]]]


 [[[4 0 3]
   [2 2 0]
   [3 0 4]]

  [[0 3 2]
   [2 0 2]
   [0 4 1]]

  [[3 2 4]
   [0 2 3]
   [4 1 0]]

  [[2 4 4]
   [2 3 3]
   [1 0 1]]

  [[4 4 3]
   

# 85. 创建一个二维数组子类，使 Z[i,j] == Z[j,i]

In [204]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  4  4  7 11]
 [ 4  6  3 14  9]
 [ 4  3  6 42 15]
 [ 7 14 42  2  8]
 [11  9 15  8  8]]


# 86. 考虑一组具有形状（n，n）的p矩阵和一组具有形状（n，1）的p向量。 如何一次计算p矩阵乘积的总和？ （结果有形状（n，1））

In [206]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


# 87. 考虑一个16x16阵列，如何获得块总和（块大小为4x4）？

In [208]:
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


# 88. 如何使用numpy数组实现游戏生命？

In [209]:
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# 89. 如何获取数组的n个最大值

In [210]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9998 9996 9995]


# 90. 给定任意数量的向量，构建笛卡尔积（每个项的每个组合）

In [211]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


# 91. 如何从常规数组创建记录数组？

In [212]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


# 92. 考虑一个大的向量Z，使用3种不同的方法将Z计算为3的立方

In [216]:
x = np.random.rand()
np.power(x,3)

0.8367169452392341

In [217]:
x*x*x

0.8367169452392341

In [230]:
np.einsum("i,i,i->i",x,x,x)

array([0.00144463, 0.59785421, 0.07460151, ..., 0.07859655, 0.00916918,
       0.6442997 ])

# 93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？

In [231]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 4 5]


# 94. 考虑10x3矩阵，提取具有不等值的行 (e.g. [2,2,3])

In [232]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 1 0]
 [3 0 0]
 [3 3 0]
 [1 2 3]
 [4 0 3]
 [0 1 2]
 [4 0 3]
 [3 0 3]
 [2 3 1]
 [0 2 4]]
[[0 1 0]
 [3 0 0]
 [3 3 0]
 [1 2 3]
 [4 0 3]
 [0 1 2]
 [4 0 3]
 [3 0 3]
 [2 3 1]
 [0 2 4]]
[[0 1 0]
 [3 0 0]
 [3 3 0]
 [1 2 3]
 [4 0 3]
 [0 1 2]
 [4 0 3]
 [3 0 3]
 [2 3 1]
 [0 2 4]]


# 95. 将一个整数向量转换为matrix binary的表现形式

In [237]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# 96. 给定一个二维数组，如何提取唯一的行？

In [234]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


# 97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数

In [235]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[3.52599316e-03, 3.03238045e-02, 1.02188438e-01, 6.65437181e-02,
        1.12881924e-01, 9.61682924e-02, 9.14630882e-02, 9.55504690e-02,
        1.14647562e-01, 3.20977265e-03],
       [5.12957271e-03, 4.41147084e-02, 1.48662519e-01, 9.68070058e-02,
        1.64219274e-01, 1.39904482e-01, 1.33059408e-01, 1.39005680e-01,
        1.66787902e-01, 4.66953889e-03],
       [8.74334358e-03, 7.51934077e-02, 2.53394884e-01, 1.65007294e-01,
        2.79911334e-01, 2.38466833e-01, 2.26799420e-01, 2.36934827e-01,
        2.84289554e-01, 7.95921712e-03],
       [2.50732640e-02, 2.15631943e-01, 7.26659859e-01, 4.73190995e-01,
        8.02701015e-01, 6.83850726e-01, 6.50392117e-01, 6.79457397e-01,
        8.15256424e-01, 2.28246265e-02],
       [1.52521929e-02, 1.31169998e-01, 4.42030856e-01, 2.87844468e-01,
        4.88287075e-01, 4.15989844e-01, 3.95636804e-01, 4.13317360e-01,
        4.95924593e-01, 1.38843354e-02],
       [1.01267751e-02, 8.70910219e-02, 2.93488752e-01, 1.91115874e-01,
   

# 98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)?

In [238]:
 phi = np.arange(0, 10*np.pi, 0.1)
 a = 1
 x = a*phi*np.cos(phi)
 y = a*phi*np.sin(phi)

 dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
 r = np.zeros_like(x)
 r[1:] = np.cumsum(dr)                # integrate path
 r_int = np.linspace(0, r.max(), 200) # regular spaced path
 x_int = np.interp(r_int, r, x)       # integrate path
 y_int = np.interp(r_int, r, y)

# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [239]:
 X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                 [1.5, 2.5, 1.0, 0.0]])
 n = 4
 M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
 M &= (X.sum(axis=-1) == n)
 print (X[M])

[[2. 0. 1. 1.]]


# 100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。
(Compute bootstrapped 95% confidence intervals for the mean of a 1D array X，i.e. resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)

In [241]:
 X = np.random.randn(100) # random 1D array
 N = 1000 # number of bootstrap samples
 idx = np.random.randint(0, X.size, (N, X.size))
 means = X[idx].mean(axis=1)
 confint = np.percentile(means, [2.5, 97.5])
 print (confint)

[-0.24967077  0.0620429 ]
